name: Unit Tests

on:
  push:
    branches: [ main ] # Assuming 'main' is the default branch. If not, adjust.
  pull_request:
    branches: [ main ] # Assuming 'main' is the default branch. If not, adjust.

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Specify Node.js versions to test on

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use a recent stable version

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 # Use a recent stable version
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install nyc for test coverage
        run: npm install -g nyc

      - name: Run unit tests with coverage
        run: nyc mocha

      - name: Check coverage thresholds
        run: nyc check-coverage --lines 80 --functions 80 --branches 80

      - name: Send notifications on test failures
        if: failure()
        run: echo "Unit tests failed. Please check the logs for details."
